In [1]:
import numpy
import math
import pandas

In [2]:
ud_train = pandas.read_csv(r'C:\Users\jyellin\re_1\Code\path_to_re\train-ud_paths_per_relation.csv')
ud_test = pandas.read_csv(r'C:\Users\jyellin\re_1\Code\path_to_re\test-ud_paths_per_relation.csv')

In [3]:
ud_train['source'] = 'train'

In [4]:
ud_test['source'] = 'test'

In [5]:
ud = pandas.concat([ud_train, ud_test])

In [6]:
ud_stats_by_relation_and_path = ud.groupby(['source','relation','path'])['id'].count().reset_index().rename(columns={'id': 'total'}).sort_values(['relation','source', 'total'], ascending=[True,True,False]).set_index(['relation','source'])
ud_stats_by_relation = ud.groupby(['source','relation'])['id'].count().reset_index().rename(columns={'id': 'total'}).sort_values(['relation','source'], ascending=[True, True]).set_index(['relation','source'])

In [7]:
paths = ud_stats_by_relation_and_path['path'].unique().tolist()
relations = ud_stats_by_relation.index.get_level_values(0).unique().tolist()

path_to_index = {k: v for v, k in enumerate(paths)}
relation_to_index = {k: v for v, k in enumerate(relations)}

totals = ud_stats_by_relation['total'].to_list()
mean_total = numpy.mean(totals)

In [8]:
relation_to_count_matrix_train = numpy.zeros((len(relations), len(paths)), dtype=numpy.intc)

for index, row in ud_stats_by_relation_and_path.iterrows():
    
    if index[1] == 'test':
        continue
    
    relation = index[0]
    path = row['path']
    
    relation_index = relation_to_index[relation]
    path_index = path_to_index[path]
    
    total = row['total']
    if total == 1:
        total = 0
    relation_to_count_matrix_train[relation_index, path_index] = total

relation_to_count_df_train = pandas.DataFrame(relation_to_count_matrix_train, index=[relations,['train']*len(relations)], columns=paths)

In [9]:
relation_to_count_matrix_train = numpy.zeros((len(relations), len(paths)), dtype=numpy.intc)

for index, row in ud_stats_by_relation_and_path.iterrows():
    
    if index[1] == 'train':
        continue
    
    relation = index[0]
    path = row['path']
    
    relation_index = relation_to_index[relation]
    path_index = path_to_index[path]
    
    total = row['total']
    if total == 1:
        total = 0
    relation_to_count_matrix_train[relation_index, path_index] = total

relation_to_count_df_test = pandas.DataFrame(relation_to_count_matrix_train, index=[relations,['test']*len(relations)], columns=paths)

In [10]:
relation_to_count_df = pandas.concat([relation_to_count_df_train, relation_to_count_df_test])

In [11]:
# create a single data frame from the total-relation counts and the relation-to-cound dataframe
temp = pandas.concat([ud_stats_by_relation,relation_to_count_df], axis=1)

# filter out all relations for which there are less than 25% of the mean total sentences in the training set
temp = temp[temp['total'] >= mean_total/10]

# normalize counts 
temp = temp.apply( lambda x: x / x['total'] * mean_total, axis=1).drop(columns=['total'])

# round up to 
relation_to_count_normalized = temp.round(0).astype(int)

In [13]:
relation_to_count_normalized.head()

                                   >appos  <appos  >conj:and >appos  \
org:alternate_names         test       63      50                11
                            train      60      50                 6
org:city_of_headquarters    test        0       0                 0
                            train       0       1                 0
org:country_of_headquarters test        0       0                 0

                                   <appos <conj:and  <nmod:as <acl  \
org:alternate_names         test                 10              5
                            train                 7              0
org:city_of_headquarters    test                  0              0
                            train                 0              0
org:country_of_headquarters test                  0              0

                                   >nmod:of >appos  <conj:or  \
org:alternate_names         test                 5         3
                            train                2         0
org:city_of_headquarters    test                 0         0
                            train                0         0
org:country_of_headquarters test                 0         0

                                   <nmod:as <acl >appos  \
org:alternate_names         test                      3
                            train                     0
org:city_of_headquarters    test                      0
                            train                     0
org:country_of_headquarters test                      0

                                   <compound <nmod:at >dobj >dep >appos  \
org:alternate_names         test                                      2
                            train                                     0
org:city_of_headquarters    test                                      0
                            train                                     0
org:country_of_headquarters test                                      0

                                   <compound <nmod:at >nmod:at >nmod:poss  \
org:alternate_names         test                                        2
                            train                                       0
org:city_of_headquarters    test                                        0
                            train                                       0
org:country_of_headquarters test                                        0

                                   ...  >appos >nmod:under  \
org:alternate_names         test   ...                   0
                            train  ...                   0
org:city_of_headquarters    test   ...                   0
                            train  ...                   0
org:country_of_headquarters test   ...                   0

                                   >compound >nmod:under  >dep >nmod:as  \
org:alternate_names         test                       0              0
                            train                      0              0
org:city_of_headquarters    test                       0              0
                            train                      0              0
org:country_of_headquarters test                       0              0

                                   >dep >nmod:of >dep  >dep >nsubjpass  \
org:alternate_names         test                    0                0
                            train                   0                0
org:city_of_headquarters    test                    0                0
                            train                   0                0
org:country_of_headquarters test                    0                0

                                   >nmod:among  \
org:alternate_names         test             0
                            train            0
org:city_of_headquarters    test             0
                            train            0
org:country_of_headquarters test             0

                                   >nmod:for >acl:in >nmod:by >compound  \
org:alternate_names         test                                      0
                            train                                     0
org:city_of_headquarters    test                                      0
                            train                                     0
org:country_of_headquarters test                                      0

                                   >nmod:to >ccomp >dobj  >nsubj >acl:relcl  \
org:alternate_names         test                       0                  0
                            train                      0                  0
org:city_of_headquarters    test                       0                  0
                            train                      0                  0
org:country_of_headquarters test                       0                  0

                                   >root >nmod:on >nmod:of
org:alternate_names         test                         0
                            train                        0
org:city_of_headquarters    test                         0
                            train                        0
org:country_of_headquarters test                         0

[5 rows x 5419 columns]

In [12]:
paths = ud_stats_by_relation_and_path['path'].unique().tolist()
relations = ud_stats_by_relation.index.get_level_values(0).unique().tolist()

scores = []

for relation in relations:
    
    test_row = relation_to_count_normalized[
        (relation_to_count_normalized.index.get_level_values(0) == relation) &
        (relation_to_count_normalized.index.get_level_values(1) == 'test')]
    
    train_row = relation_to_count_normalized[
        (relation_to_count_normalized.index.get_level_values(0) == relation) &
        (relation_to_count_normalized.index.get_level_values(1) == 'train')]

    
    if (len(test_row) == 0 or len(train_row) == 0):
        continue
    
    numerator = 0
    denominator = 0
    
    for path in paths:
        test_row_count = 0
        if len(test_row[path].values) > 0:
            test_row_count = test_row[path].values[0]
            
        train_row_count = 0
        if len(train_row[path].values) > 0:
            train_row_count = train_row[path].values[0]
        
        numerator = numerator + min(test_row_count, train_row_count)
        denominator = denominator + max(test_row_count, train_row_count)
    
    if denominator > 0:
        append((relation, '{} (test)'.format(relation), numerator / denominator ))

        
work = relation_to_count_normalized[relation_to_count_normalized.get_index(1) == 'train'].to_numpy()
        
for i, i_relation in enumerate(relations):
    i_row = work[i]

    for j, j_relation in enumerate(relations[i+1:]):
        j_row = work[i+1+j]

        numerator = 0
        denominator = 0
        for k, k_path in enumerate(paths):
            numerator = numerator + min(i_row[k], j_row[k])
            denominator = denominator + max(i_row[k], j_row[k])
        
        jaccard_weighted_scores.append((i_relation, j_relation, numerator / denominator ))

In [13]:
score_df = pandas.DataFrame.from_dict(scores,  orient='index', columns=['score']).sort_values(['score'], ascending=[False] )
score_df

                                        score
org:alternate_names                  0.696133
per:origin                           0.539568
per:title                            0.512563
per:age                              0.512077
org:website                          0.491379
org:top_members/employees            0.487047
per:parents                          0.324468
org:subsidiaries                     0.316176
org:founded                          0.286585
per:employee_of                      0.266667
per:countries_of_residence           0.245902
per:cities_of_residence              0.241935
per:spouse                           0.239521
per:schools_attended                 0.237805
org:country_of_headquarters          0.228070
org:city_of_headquarters             0.218085
org:founded_by                       0.201970
per:siblings                         0.164557
per:other_family                     0.158730
per:date_of_death                    0.136646
org:stateorprovince_of_headquarters  0.133333
per:stateorprovinces_of_residence    0.110294
org:parents                          0.105263
per:children                         0.086957
per:charges                          0.074627
per:cause_of_death                   0.016484
per:religion                         0.000000
org:members                          0.000000
per:city_of_death                    0.000000